### ISSUE TITLE
Double page for some files

### ISSUE THREAD

**Issue by payamomrani** [ottosmops/pdftothumb#1]
hi
thank you for produce this package
when i convert some PDF , two page together be create 
for example if PDF has 16 page ,for page 1 create page 1 and last page side by side
how can i fix ?

thanx

**Comment by ottosmops** [comment]
Since this package uses `pdftoppm` you should check the manual: https://linux.die.net/man/1/pdftoppm

You can override all options (cf. README). If you know the number of pages you should be able to create a thumb of the last page.
 
After that you could join the results (e.g. https://github.com/Intervention/image/issues/376), if it is that what you want.

I dont think that´s a good solution.

In this case i think this package is better: https://github.com/spatie/pdf-to-image
